# Document Configuration for Birla Caps Corporate Website
documents:
  financial_reports:
    - id: "annual_report_2024"
      title: "Annual Report 2024"
      type: "ANNUAL_REPORT"
      description: "Comprehensive annual report showcasing financial performance, governance, and strategic initiatives for fiscal year 2024"
      fiscal_year: 2024
      file_path: "/attached_assets/NISHAKANT-SHUKLA_1755673329540.pdf"
      file_name: "Annual_Report_2024.pdf"
      category: "finance"
      tags: ["annual", "performance", "governance", "financial"]
      priority: "HIGH"
      featured: true
      
    - id: "quarterly_q4_2024"
      title: "Q4 2024 Quarterly Results"
      type: "QUARTERLY_RESULT"
      description: "Fourth quarter financial results and business performance metrics"
      fiscal_year: 2024
      file_path: "/attached_assets/Golu bhayai resume_1755673329540.pdf"
      file_name: "Q4_2024_Results.pdf"
      category: "finance"
      tags: ["quarterly", "results", "performance"]
      priority: "HIGH"
      featured: true

  announcements:
    - id: "board_meeting_2024"
      title: "Board Meeting Announcement - December 2024"
      type: "ANNOUNCEMENT"
      description: "Notice of upcoming board meeting and key agenda items for stakeholder review"
      file_path: "/attached_assets/Keywords and Identifiers_1755673329541.pdf"
      file_name: "Board_Meeting_Dec_2024.pdf"
      category: "governance"
      tags: ["board", "meeting", "governance"]
      priority: "NORMAL"
      featured: false

  governance:
    - id: "governance_policy_2024"
      title: "Corporate Governance Policy 2024"
      type: "GOVERNANCE"
      description: "Updated corporate governance framework and compliance guidelines"
      file_path: "/attached_assets/NISHAKANT-SHUKLA_1755673329540.pdf"
      file_name: "Governance_Policy_2024.pdf"
      category: "governance"
      tags: ["governance", "policy", "compliance"]
      priority: "HIGH"
      featured: true

# UI Configuration
ui_settings:
  theme:
    primary_color: "#1e40af"
    secondary_color: "#f8fafc"
    accent_color: "#3b82f6"
    
  layout:
    cards_per_row: 3
    show_featured_first: true
    enable_search: true
    enable_filters: true
    
  pdf_viewer:
    enable_inline_preview: true
    max_preview_pages: 5
    enable_download: true
    enable_print: true
    zoom_levels: [0.5, 0.75, 1.0, 1.25, 1.5, 2.0]

# Metadata
metadata:
  last_updated: "2024-12-20"
  version: "1.0"
  maintained_by: "Birla Caps IT Team"